<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<!--[if IE 7]><html class="ie7" lang="en"><![endif]-->
<!--[if IE 8]><html class="ie8" lang="en"><![endif]-->
<!--[if IE 9]><html class="ie9" lang="en"><![endif]-->
<!--[if gt IE 9]><!--><html lang="en"><!--<![endif]-->
<head>
<?php
echo $this->headTitle();
echo $this->headMeta();
echo $this->headLink();
echo $this->headStyle();
?>
<!--[if IE 6]>
<link rel="stylesheet" type="text/css" href="/public/css/iefix.css" media="screen" />
<![endif]-->
</head>
<body>
    <?php echo $this->translate("TXT.SITENAME");  ?><br>
    <?php echo $this->translate("TXT.HOMEPAGE"); ?></br>
    <?php
        //hien thi noi dung view
        echo $this->layout()->content;
    ?>
<?php //echo $this->headScript(); ?>

</body>
</html>
